tensorflow:
    build: ./
    ports: 
        - "8888:8888"
    volumes:
        - "./content:/var/www:rw"
    working_dir: "/var/www"
    command: jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root --notebook-dir=/var/www
